### ISSUE TITLE
stuck after executing the command:  grgsm_decode -m TCHF ...

### ISSUE THREAD

**Issue by prkrmx** [ptrkrysik/gr-gsm#223] opened 2016-09-26 08:31 UTC
Hello All
I got stuck in the last step
can't exit (complete the process) after running **grgsm_decode** in the **TCHF** mode
any suggestions ?
thx

**Comment by ptrkrysik** [comment] 2016-10-01 19:42
@prkrmx , if the problem is that grgsm_decode doesn't exit when decoding traffic channels - the reason is that I changed it to use pdu to stream conversion. 

The culprit was GNU Radio not exiting when such block was used. The topic of pdu to stream converter impact on exiting was discussed here:
https://lists.gnu.org/archive/html/discuss-gnuradio/2016-07/msg00296.html

The problem is fixed in new GNU Radio versions:
https://lists.gnu.org/archive/html/discuss-gnuradio/2016-07/msg00349.html

Solution for you is to use the newest GNU Radio.

**Closed by ptrkrysik** 2016-10-01 19:42 UTC
