### ISSUE TITLE
grgsm_livemon error running

### ISSUE THREAD

**Issue by engrmasood2002** [ptrkrysik/gr-gsm#292] opened 2017-07-16 11:17 UTC
Hi
I am getting error 
GSM input adaptor(9): insufficient connected input ports (1 needed, 0 connected)

when running grgsm_livemon in ubuntu 16.04 LTS with gnuradio 3.7.9 following instructions from 
https://github.com/ptrkrysik/gr-gsm/wiki/Installation

I also tried with  gnuradio 3.7.8 with instructions from
https://github.com/ptrkrysik/gr-gsm/issues/135   
and i got following error in this case
....
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr/runtime_swig.py", line 3030, in primitive_msg_connect
    return _runtime_swig.hier_block2_sptr_primitive_msg_connect(self, *args)
RuntimeError: invalid msg port in connect() or disconnect()

Any idea what could be wrong. PyBOMBS install correctly in both cases.

**Comment by engrmasood2002** [comment] 2017-07-17 04:46
Just wanted to update.
Problem solved by fresh installation as per gr-gsm installation wiki.

**Comment by E3V3A** [comment] 2017-07-18 09:07
@engrmasood2002 If the problem is solved, and issue invalidated, please close it.

**Closed** 2017-07-18 19:44 UTC
