### ISSUE TITLE
TypeError: msg_connect() takes exactly 5 arguments (3 given) (Raspberry Pi 3)

### ISSUE THREAD

**Issue by greg5678** [ptrkrysik/gr-gsm#199] opened 2016-06-24 20:32 UTC
I have followed the instructions to install gr-gsm on my Raspberry Pi 3. My pi is running gnuradio 3.7.5. It gives me this error TypeError: msg_connect() takes exactly 5 arguments (3 given). My pi is running Raspbian 4.4.13-v7

**Comment by ptrkrysik** [comment] 2016-07-15 13:27
This is duplicate of #187

**Closed by ptrkrysik** 2016-07-15 13:27 UTC
